### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by dotnize** [ggonzaga29/pdf-to-bionic#2]
- [x] https://github.com/ggonzaga29/pdf-to-bionic/commit/36e18a42c7094af389f295bb658efd0e826897e3 keep original file name before uploading to firebase
- [x] https://github.com/ggonzaga29/pdf-to-bionic/commit/ee24689e2f27380a1c90467455662be799ca9f46 keep original pdf style/layout (use 3rd party api)
- [x] https://github.com/ggonzaga29/pdf-to-bionic/commit/4d69e3eeb87652f0604d44b3221da76a5ea16c7e proper error handling
- [ ] improve code readability (cleanup, refactor, modularise)
